### ISSUE TITLE
Implement eaf apps as minor-modes

### ISSUE THREAD

**Issue by clemera** [manateelazycat/emacs-application-framework#117]
Currently `eaf-mode-map` is used by every app. This means if you use multiple apps all have the keymap from the last started app, which is not good ;)

Another problem with the current approach is that if the user has some minor mode which bindings conflict with those of the eaf-mode-map the eaf bindings have no precedence and the minor mode bindings are used.

I think implementing apps as minor modes would be a good idea. Then users also could change bindings by just changing `eaf-browser-mode-map` for example. What do you think? Should I start working on this?

**Comment by MatthewZMD** [comment]
When I was working on implementing C-h m with dummy variables, I also thought able organizing them with minor modes. However it turns out not looking very good on C-h m -- because all specific keybindings will be somewhere burried under the Minor mode spec ocean, not very helpful for someone wanting to quickly check keybindings by C-h m

**Comment by clemera** [comment]
> However, it turns out not looking very good on C-h m

An alternative I can think of would be to use `C-h v eaf-browser-mode-map` to check the bindings. When executing a command using `counsel-M-x` and I believe `helm` bindings are shown inline, too. A custom `describe-eaf-bindings` would also be possible.

> I can see this issue in a lot of emacs packages, that some minor mode keybinding overrides a major mode keybinding.

I think when inside an app the eaf bindings should have precedence over all other bindings the user has currently defined. I see no reasons users would define other minor-modes for eaf buffers so there would be no conflict in this case. Having a function to change the bindings is nice but it's additional work we could save users from.

**Comment by clemera** [comment]
> We could replace the keymaps depending on the current EAF app buffer the user is currently in instead of replacing them during app start-up, that's a possible solution.

If we should decide doing that we could define a buffer local `eaf-mode-map` in each app buffer and then set the default value to the buffer local value the user is currently in. I'm still in favor for using minor-modes, though ;)

**Comment by clemera** [comment]
One other solution I just thought of to have always precedence for the app keys would be to use a buffer local `overriding-terminal-local-map` but that may introduce other problems, I'm not aware of.

**Comment by manateelazycat** [comment]
I personally do not care about this feature, because I basically do not see the key details. (Perhaps because I was too familiar with this project, hahahaha)

Anyway, any improvement are welcome! ;)

**Comment by MatthewZMD** [comment]
Well, we can also ask the person who raised this feature request at #82 @stardiviner for opinions on this topic

**Comment by stardiviner** [comment]
I watched @MatthewZMD and @clemera 's opinions, both considered some edge cases. In my personal opinion, I think this will not be a simple small feature, because eaf's principle is to integrate Qt application into Emacs. Some Qt applications have many keybindings.
About implementation, I think both of you have thinked all of situations, I can't give more idea. I think minor mode is a good solution. This will isolate different application, and make writing code simpler if it is?

**Comment by manateelazycat** [comment]
I don't care this feature, if you want improve it, welcome to PR.

Thanks for recently patches, awesome man!

**Comment by clemera** [comment]
@manateelazycat I thought that bindings would also not work with two apps in parallel but I was wrong, only the display with `C-h m` is wrong. In this case it's not so bad as I thought.

**Comment by stardiviner** [comment]
@clemera Awesome!

**Comment by stardiviner** [comment]
@clemera Awesome!
