### ISSUE TITLE
Add wiki?

### ISSUE THREAD

**Issue by clemera** [manateelazycat/emacs-application-framework#136]
I just created a code snippet to use `helm-filtered-bookmarks` to categorize bookmarks by eaf app type. This is not suitable to be included in eaf but some people would probably like to add it to their config. Github wiki is a nice place to add such snippets, see [swiper wiki](https://github.com/abo-abo/swiper/wiki) for example, hence my question if you would add a wiki.

You could move other things like hacking.md and your todo list there, too if you like. Then you would have all additional info in once place.

**Comment by manateelazycat** [comment]
yes wiki is good idea

**Comment by MatthewZMD** [comment]
Many things from README can be moved to wiki as well :)

**Comment by manateelazycat** [comment]
@clemera @MatthewZMD Only I can do to create a Wiki?

**Comment by MatthewZMD** [comment]
Yes, and only collaborators with write access can edit the wiki by default.

https://help.github.com/en/github/building-a-strong-community/about-wikis

**Comment by MatthewZMD** [comment]
@clemera Hey I am curious to know what distro and DE/WM that you are using. I am trying to have a brief idea of how compatible is EAF with some other environments. There are bug reports from time to time that may due to the incompatibility with their machine.

 I use Manjaro with KDE and I believe @manateelazycat uses the same, and I've only tested EAF on another Lubuntu with LXDE, which works pretty nicely.

**Comment by clemera** [comment]
@MatthewZMD  I'm using Gnome 3

**Comment by manateelazycat** [comment]
@MatthewZMD @clemera I have add you guys in collaborators, welcome to build wiki. ;)

**Comment by clemera** [comment]
Thanks, I started adding a page for integration with Helm, one can clone the wiki using: 

    git clone git@github.com:manateelazycat/emacs-application-framework.wiki.git
