### ISSUE TITLE
Support mobi and azw3 

### ISSUE THREAD

**Issue by stardiviner** [manateelazycat/emacs-application-framework#187]
EAF has PDF document support already. Next maybe ebooks like `epub`, `mobi` `azw3` support? Calibra already has command `ebook-viewer`. Is is possible to embed it directly?

**Comment by manateelazycat** [comment]
I believe EAF PDF Viewer has support epub since it's base on pymupdf library.
You can check pymupdf file format at https://pypi.org/project/PyMuPDF/

EAF only can embed application that develop follow by EAF framework, EAF is not window manager that can embed any program in Emacs.
So ebook-viewer won't work like you expected.

mobi and azw3 support is not in my plan, hope some hacker can do that. ;)

**Comment by stardiviner** [comment]
I see. Thanks @manateelazycat :)

**Comment by manateelazycat** [comment]
epub has support by pdf-viewer
azw3 is DRM format, no library to parse it.
mobi is no plan to support it.

Close issue, sorry.

**Comment by stardiviner** [comment]
I found an Python library might can parse Kindle some ebook formats.
Might be useful, just mark it here.

https://github.com/kevinhendricks/KindleUnpack
