### ISSUE TITLE
pdf: keyboard select

### ISSUE THREAD

**Issue by xcapegoat** [manateelazycat/emacs-application-framework#296]
Hey, 

It would be great to support some keyboard actions since this is emacs. I would like to do this myself but I don't know coding well. 

For instance: 

- keybind to mark the (whole) current page for selection/copying.

Then we can switch to another buffer with the copied text. 

I have been trying to find a pdf viewer allows such keyboard actions but they are all problematic. For example, pdf-tools emacs extension does but it only renders one page at a time when scrolling, which makes the overall pdf experience very slow.

I don't see any such features on the todo list so I guess it's not likely to see in the future? 

Thanks for reading.

**Comment by manateelazycat** [comment]
It's not easy to implement, since there's no row or column concept in pdf library, just x or y coordinate.

And PDF library have it's own layout, not just text like Emacs, there have image, formula, form or any other complicated thing in PDF.

I don't think we can select text with keyboard like Emacs.
