### ISSUE TITLE
Multiple instances of Emacs can not simultaneously run EAF

### ISSUE THREAD

**Issue by d3v-S** [manateelazycat/emacs-application-framework#343]
Reproduction:
- open 2 emacs
- try opening url
- one will open url in eaf & other will report *eaf* finished

Buffer *eaf* shows - EAF process already running.

How can we run EAF browsers in multiple instances of emacs?

**Comment by MatthewZMD** [comment]
This is a limitation of the current EAF design.

There're two workarounds if you really like multiple frames:
1. use `emacs --daemon`
2. use `C-x 5 2` or `M-x make-frame-command` to open a new frame.

Since these workarounds work fairly well, I don't think it's worthwhile to invest extra time in changing EAF design just to implement this feature.

Feel free to play with the EAF source code to implement this feature if you wish, and submit a PR.

**Comment by d3v-S** [comment]
Are the browser tabs running in EAF are running on a different thread than emacs? I mean to ask, if the browser-tab is going down/lagging, it won't lag the emacs?
