### ISSUE TITLE
Other commands do not work in the js-video-player mode except close and toggle play

### ISSUE THREAD

**Issue by duzaichuan** [manateelazycat/emacs-application-framework#399]
As described in the title...

Except using the default key bindings, I also tried M-x finding those commands (forward and backward play, etc), but failed.

If you guys have any clue

Thank you!

**Versions**
The latest master branch
Emacs 27.1
Manjaro

**Comment by MatthewZMD** [comment]
Please check the [wiki](https://github.com/manateelazycat/emacs-application-framework/wiki/Keybindings#the-keybinding-of-eaf-js-video-player)

**Comment by manateelazycat** [comment]
check wiki

**Comment by duzaichuan** [comment]
I did not make it clear, apologize. I did read and check the wiki frequently and tried to use those keybindings of js-video-player, but those just does not work except SPC and x.

**Comment by MatthewZMD** [comment]
What does `C-h k <not-working-key>` give you?

**Comment by duzaichuan** [comment]
They give `eaf-send-key`. `SPC, x` and volume `j,k` work well and `C-h k` give their corresponding commands.

**Comment by MatthewZMD** [comment]
@manateelazycat Can you take a look, I haven't try js-video-player

**Comment by manateelazycat** [comment]
@duzaichuan

Thanks for report.

I believe it's my fault and I have fix this issue in newest version.

Fix solution at https://github.com/manateelazycat/emacs-application-framework/commit/c2fc51c8a4b8ff882cd8e1f46c9d581fb3d2dd45

The cause is eaf--generate-keybinding-map will test symbol is built-in elisp function or symbol string include "_", if both not, use intern call it as elisp function.

That's why decrease_volume work and forward not work, because decrease_volume include char _ and forward not include char _.

Newest version, I have adjust logic, if a command string is build-in elisp function or include char "-" , call it at elisp side, otherwise call it at python side.

**Comment by duzaichuan** [comment]
The solution works well. Thanks for the explanation and you guys' work on this great project!
