### ISSUE TITLE
Provide general instructions for installing on MacOS (non-X Windows)

### ISSUE THREAD

**Issue by rswgnu** [manateelazycat/emacs-application-framework#462]
Is there anything that really depends on X in here or could the instructions, especially the package dependencies, be adapted for MacOS?  That would open this open to a large set of additional users.

**Comment by MatthewZMD** [comment]
Please have a look at the README on why MacOS currently is not supported:
```
### EAF is (currently) Linux only. Why?
1. DBus is Linux-specific technology, it's difficult to support DBus in other operating systems.
2. Qt5's QGraphicsScene technology does not work on MacOS.

If you've figure them out, PRs are always welcome!
```
EAF currently platform-limited is not due to an issue with the external dependencies that you'd have to install, but a technical limitation on how EAF itself is been implemented at the moment.

Since we don't use Windows/MacOS, we don't have the resource or time to resolve this problems, so we really need help from the community to try them out :-)

**Comment by rswgnu** [comment]
Thanks for the explanation.  One of the great traits of Emacs is its multi-platform operation and uniformity, allowing a common operating environment across OSes.  I think the work is great but hard to leverage widely because of its OS-centricity right now.

**Comment by manateelazycat** [comment]
MacOS need Mac hacker to help, EAF developers not very good at operating system technology for Mac platforms.

Close issue, sorry.
