### ISSUE TITLE
Use emacs-application-framework in python environment managed by pyenv/virtualenv/conda.

### ISSUE THREAD

**Issue by hongyi-zhao** [manateelazycat/emacs-application-framework#469]
Based on the notes of the [installation guide](https://github.com/manateelazycat/emacs-application-framework#install), EAF depends heavily on python ecosystem. As we all know, python environments are often installed and managed through pyenv/virtualenv/conda.

So, I want to know whether EAF is also compatible/workable with the above mentioned python package management frameworks.

Any hints will be highly appreciated.

Regards,
HY

**Comment by manateelazycat** [comment]
I just use arch, don't use pyenv/virtualenv/conda.

**Comment by MatthewZMD** [comment]
> I want to know whether EAF is also compatible/workable with the above mentioned python package management frameworks.

Try them out yourself and provide feedback to us, that'd be appreciated.

**Comment by hongyi-zhao** [comment]
I'll try and feedback if any valuable experience is gained.

**Comment by Aeres-u99** [comment]
@hongyi-zhao There is a simpler way to actually have multiple python environment and package isolation. It seems that eaf respects the Launching programs Environment so you can do the following steps to have your own virtualenv for the same,
1. Create a virtual environment and note its path, lets say your user is `user` and virtualenv is in pyenv directory, the `source` path will be, `/home/user/pyenv/bin/activate`.
2. Create a simple script somewhere, and lets call it `launcher.sh` the job of launcher.sh is to source the virtualenv file and launch emacs, create `launcher.sh` with following content
```
source /home/user/pyenv/bin/activate
emacs &
```
(don't forget to `chmod +x launcher.sh`)
3. Now you can create a desktop entry for this with the following content (creating desktop entry basically means creating a .desktop file and moving it to ~/.local/share/applications)
```
[Desktop Entry]
Name=Emacs (Custom)
GenericName=Text Editor
Comment=Edit text
MimeType=text/english;text/plain;text/x-makefile;text/x-c++hdr;text/x-c++src;text/x-chdr;text/x-csrc;text/x-java;text/x-moc;text/x-pascal;text/x-tcl;text/x-tex;application/x-shellscript;text/x-c;text/x-c++;
Exec=/home/user/launcher.sh
Icon=emacs
Type=Application
Terminal=false
Categories=Development;TextEditor;Utility;
StartupWMClass=Emacs
```
And save it in `~/.local/share/applications/EmacsCustom.desktop`
now you should be able to see the desktop entry and if you feel like launching from commandline, even ./launcher.sh will work.

@manateelazycat @MatthewZMD Do you think we should also document this (possibly in another file) because having separate python environment will be very helpful. And will prevent breaking of any emacs ecosystem if system upgrade causes issue (like we recently had lots of problems with python 3.9)

**Comment by MatthewZMD** [comment]
> @manateelazycat @MatthewZMD Do you think we should also document this (possibly in another file) because having separate python environment will be very helpful. And will prevent breaking of any emacs ecosystem if system upgrade causes issue (like we recently had lots of problems with python 3.9)

Feel free to do it yourself in the Wiki.

**Comment by Aeres-u99** [comment]
yay! Thanks. This way I will be able to play with python emacs and see if there is somethings that can be extended

**Comment by manateelazycat** [comment]
> @hongyi-zhao There is a simpler way to actually have multiple python environment and package isolation. It seems that eaf respects the Launching programs Environment so you can do the following steps to have your own virtualenv for the same,
> 
> 1. Create a virtual environment and note its path, lets say your user is `user` and virtualenv is in pyenv directory, the `source` path will be, `/home/user/pyenv/bin/activate`.
> 2. Create a simple script somewhere, and lets call it `launcher.sh` the job of launcher.sh is to source the virtualenv file and launch emacs, create `launcher.sh` with following content
> 
> ```
> source /home/user/pyenv/bin/activate
> emacs &
> ```
> 
> (don't forget to `chmod +x launcher.sh`)
> 3. Now you can create a desktop entry for this with the following content (creating desktop entry basically means creating a .desktop file and moving it to ~/.local/share/applications)
> 
> ```
> [Desktop Entry]
> Name=Emacs (Custom)
> GenericName=Text Editor
> Comment=Edit text
> MimeType=text/english;text/plain;text/x-makefile;text/x-c++hdr;text/x-c++src;text/x-chdr;text/x-csrc;text/x-java;text/x-moc;text/x-pascal;text/x-tcl;text/x-tex;application/x-shellscript;text/x-c;text/x-c++;
> Exec=/home/user/launcher.sh
> Icon=emacs
> Type=Application
> Terminal=false
> Categories=Development;TextEditor;Utility;
> StartupWMClass=Emacs
> ```
> 
> And save it in `~/.local/share/applications/EmacsCustom.desktop`
> now you should be able to see the desktop entry and if you feel like launching from commandline, even ./launcher.sh will work.
> 
> @manateelazycat @MatthewZMD Do you think we should also document this (possibly in another file) because having separate python environment will be very helpful. And will prevent breaking of any emacs ecosystem if system upgrade causes issue (like we recently had lots of problems with python 3.9)

we can write those on wiki, wiki can edit public

keep readme simple
