### ISSUE TITLE
Mention system Qt packages needed for running eaf

### ISSUE THREAD

**Issue by Compro-Prasad** [manateelazycat/emacs-application-framework#50]

**Comment by manateelazycat** [comment]
Just install Qt5 and runing with one of below DE: gnome, kde, dde, unity

**Comment by Compro-Prasad** [comment]
I had to install more than just Qt5. It was `qt5-webengine` which was a dependency for pdf reader.

**Comment by manateelazycat** [comment]
> I had to install more than just Qt5. It was `qt5-webengine` which was a dependency for pdf reader.

This is because each ilnux distribution divides Qt into a lot of packages.
You don't need to care about the package if you install the Qt5 binary package directly from the official.

Sorry, I don't have time to analyze which packages are needed for each linux distribution.

Of course, if you feel it is necessary, welcome to commit a patch to fix doc.
