### ISSUE TITLE
EAF-browser reloads page when text is entered in search field at vk.com (and more)

### ISSUE THREAD

**Issue by rustamusmanov973** [manateelazycat/emacs-application-framework#549]
1. EAF-browser reloads page (vk.com) when text is entered in search field
I am registered at vk.com messenger. 
Then in left side menu: messages -> search for messages. Each letter typed causes eaf-browser to reload the hole page (~1s of black screen) which makes browsing experience quite rough.
2. Images loading about a second (others browsers: instantly) at vk.com:
At e.g. [this](https://vk.com/durov?z=photo1_456287386%2Fphotos1)  page press right arrow to select next photo and you will experience black screen (~1s). Other browsers allow to switch photos without noticeable delay. 
2. IMHO EAF-browser loads pages slower (additional lag about a second) than others (chrome, firefox, chromium, next, quitebrowser, wget, eww, e3m). 
Can it be fixed in theory? Is it a real limitation of EAF-browser?

**Comment by manateelazycat** [comment]
Has fixed by newest version.

Because EAF browser has dark mode, and darkmode.js is not perfect, so EAF browser draw background when page url, until page load finish. This way is no effect for most website, but not good for some website, such as vk.com.

About Point 3, EAF load page should same with browser that base on Qt webengine, and will slower than Chrome.
