### ISSUE TITLE
Send files opened in eaf throu telega

### ISSUE THREAD

**Issue by OrionRandD** [manateelazycat/emacs-application-framework#675]
Could you make eaf work with 
"telega-buffer-file-send"
When I open a image in Emacs, eaf opens my (jpg, png, jpeg, etc.)
But it is unable to be integrated with Telega for sending them to other
chat users.
This happens because eaf sees the file path as?
e.g. 
file:///~/Pictures/misc/you_are_the_research.jpeg
and Telega cant locate such kind of addresses

I am sure the main Telega dev will be willing to help that integration...

https://github.com/zevlg/telega.el

**Comment by zevlg** [comment]
`telega.el` uses `(buffer-file-name)` to get the filename of the buffer, then checks it with `file-remote-p` to make a local copy in case remote file is in use, making it possible to send remote files 

In any case `file:///~/path` form is a bit misleading, because `file://` is a scheme, and the resulting path will be `/~/path` which is not deterministic, i.e. `(expand-file-name "/~/tmp")` won't expand it to absolute path

**Comment by BlindingDark** [comment]
@zevlg We can use `eaf-get-path-or-url` to get the filename.
So in `telega-buffer-file-send`, we can do something like
```
;; ...
         (file
          (or (buffer-file-name)
              (when (eq 'dired-mode major-mode)
                (seq-filter #'file-regular-p (dired-get-marked-files)))
              (when (eq 'eaf-mode major-mode)
                (eaf-get-path-or-url))
              (user-error (concat "Can't send current buffer, "
                                  "it does not have corresponding file")))))
;; ...
```

**Comment by MatthewZMD** [comment]
Great addition!
