### ISSUE TITLE
How to independently scroll two PDF files opened in two buffers side by side?

### ISSUE THREAD

**Issue by XushanLu** [manateelazycat/emacs-application-framework#700]
- When the same PDF file is opened with EAF in two buffers side by side, scrolling any of them would cause both to scroll. 

- Is there a way to scroll them independently?

**Comment by manateelazycat** [comment]
First version of EAF can do that.
But I remove this feature since Browser hard to implement independently scroll.

Because it's too complicated for developer if some app allowed independently scroll, and some app not allowed.

As a trick, you can rename pdf with another name, for view different part of pdf side by side.

**Comment by MatthewZMD** [comment]
Use `C-u eaf-open` to open another EAF buffer of the same file, then you can do it.
